const Discord = require("discord.js")
const fs = require("fs")
const talkedRecently = new Set();

exports.run = (client, message, args) => {

    message.delete(message)
            let hex = '#'+(Math.random()*0xFFFFFF<<0).toString(16);
            let embed = new Discord.RichEmbed()
            .setTitle('__Help Command!__')
            .addField('***Awesome alts that you can get:***', '­­­')
            .addField('`MC Java Edition:`', `*g.minecraftgen*`)
            .addField('`Spotify:`', `*g.spotifygen*`)
            .addField('`Steam:`', `*g.steamgen*`)
            .addField('`Origin:`', `*g.origingen*`)
            .addField('`Nordvpn:`', `*g.nordvpngen*`)
            .addField('`Hulu:`', `*g.hulugen*`)
            .addField('`Disney+:`', `*g.disneygen*`)
            .addField('`Mailaccess:`', `*g.mailaccessgen*`)
            .addField('Crunchyroll:', `*g.crunchyrollgen*`)
            .addField('Nitro:', `*g.nitrogen*`)
            
            .addField(`Donate to help the Owner!!\nDo: **g.donate** `, '­­­')
            .addField(`You can suggest your accountd ideas!\nDo: **>suggest**`, '­­­')
            .addField(`To see my stock\nDo: **g.stock**`, '­­­')
            .addField(`✔️Click Here For The Support **__Server__**!`, `[***Here!!***](https://dsc.gg/genz-rewards)`, true)
            .setThumbnail(message.author.avatarURL)
            .setColor(hex)
            .setTimestamp()
            .setFooter(`Generated by: ${message.author.tag}`)
            message.channel.send(embed)
}