const Discord = require("discord.js")
const fs = require("fs")
const talkedRecently = new Set();

exports.run = (client, message, args) => {

    message.delete(message)
            let hex = '#'+(Math.random()*0xFFFFFF<<0).toString(16);
            let embed = new Discord.RichEmbed()
            .setTitle('__genZ stock 🍎__')
            .addField('`MC Java Edition:`', `*Restocking 🔵*`)
           .addField('`spotify:`', `*Restocking 🔵*`)
            .addField('`Steam:`', `*Restocking 🔵*`)
            .addField('`Origin:`', `*Restocking 🔵*`)
            .addField('`Nordvpn:`', `*Restocking 🔵*`)
            .addField('`Hulu:`', `*Restocking 🔵*`)
            .addField('`Disney+:`', `*Restocking 🔵*`)
            .addField('`Mailaccess:`', `*In stock :green_circle:*`)
            .addField('`crunchyroll:`', `*Restocking 🔵*`)
          
            .addField('`nitro:`', `**In Stock :green_circle: **`)
            .addField('`-------------------`', `**UPDATING STOCK EVERY 24 HOURS**`)
            .setThumbnail(message.author.avatarURL)
            .setColor(hex)
            .setTimestamp()
            .setFooter(`Generated by: ${message.author.tag}`)
            message.channel.send(embed)
            ```js
// Here's an example if you got multiple:
const fs = require('fs')
const example = dirname + "/" + "example" + ".txt";
const example2 = __dirname + "/" + "example2" + "disney.txt";

// Here we give the directory

fs.readFile(example, "utf8", (err, exdata) => {
    fs.readFile(example2, "utf8", (err, ex2data) => {

    // Here we're reading the file!
    let examplestock = exdata.split('\n').length - 1
    let examplestock2 = ex2data.split('\n').length - 1

    // Now we're gonna check the length ^^
    let emb = new discord.MessageEmbed()
        .setTitle('Stock:')
        .addField('Example:', examplestock, true)
        .addField('Example 2:), examplestock2, true)
        .setColor('RANDOM')
    message.channel.send(emb)
})```
}